apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cmsnesia-storage.fullname" . }}
  labels:
    {{- include "cmsnesia-storage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cmsnesia-storage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cmsnesia-storage.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP